docs: Add LICENSE of errorutil
mathpresso/go-utils pull request #8
Opened 2022-09-07 08:55 UTC by kde713

2022-09-07 08:56 UTC, nutell approved these changes

2022-09-07 13:51 UTC, ElonKim requested changes

2022-09-07 13:51 UTC, ElonKim commented on errorutil/LICENSE
> +   * Neither the name of Google Inc. nor the names of its
`Google Inc.` 는 바꿔야 할 것 같아요.

2022-09-07 16:54 UTC, kde713 commented on errorutil/LICENSE
> +   * Neither the name of Google Inc. nor the names of its
Replaced in [701000a](https://github.com/mathpresso/go-utils/pull/8/commits/701000aaa5135f3de671acffaabad44ea612f253)

2022-09-08 01:46 UTC, ElonKim approved these changes
우리 회사 영문 명칭은 "Mathpresso Inc." 이라고 합니다.
이걸로 변경하면 될 것 같습니다.

2022-09-08 01:46 UTC, ElonKim commented on errorutil/LICENSE
> +Copyright (c) 2022 Mathpresso. All rights reserved.
```suggestion
Copyright (c) 2022 Mathpresso Inc. All rights reserved.
```

2022-09-08 01:46 UTC, ElonKim commented on errorutil/LICENSE
> +   * Neither the name of Mathpresso nor the names of its
```suggestion
   * Neither the name of Mathpresso Inc. nor the names of its
```

2022-09-08 02:12 UTC, kde713 commented
@ElonKim 꼼꼼하게 챙겨주셔서 감사합니다!

2022-09-08 04:53 UTC, 2minchul approved these changes

2022-09-08 04:54 UTC, merged